# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhXi-74Tr6poCZVzaWVYpUNqEqBi5xF3
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df=pd.read_csv( '/content/sample_data/Titanic_Dataset.csv' )
df

df.shape

df.info()

#handling missing values
df.isna().sum()

#empty columns
na_variables = []
for series in df.columns:
  if df[series].isna().sum() > 0:
    na_variables.append(series)
    print(f"Column which consists null values: {series}")

#Filling up the missing values with the Median
numerical_na_variables = []
categorical_na_variables = []
for series in na_variables:
  if df[series].dtype == 'float64' or df[series].dtype == 'int64':
    numerical_na_variables.append(series)
  elif df[series].dtype == "O":
    categorical_na_variables.append(series)
  else:
    pass
for series in numerical_na_variables:
 df[series].fillna(df[series].median(), inplace=True)
 
df.head()

df.isna().sum()

#Filling up the missing values with 'Missing'
for series in categorical_na_variables:
 df[series].fillna('Missing', inplace=True)
 
df.head()

#Here we can Identify the Numerical Variables:
numerical_variables = ["Age", "Fare"]
#Also, here we can Identify the Categorical Variables:
categorical_variables = ["Survived", "Pclass", "Sex", "SibSp", "Parch", "Embarked"]

df.plot()

#Handling Outliers

plt.figure(figsize = (15,10), facecolor='white')
graphplot = 1
for column in numerical_variables:
  if graphplot<=6:
    ax = plt.subplot(2,3,graphplot)
    sns.boxplot(df[column])
    plt.xlabel(column,fontsize=15)
    graphplot+=1
    plt.show()